### PR TITLE
Adding A Break Statement So The Program Wont Run Forever 😊

### PR DESCRIPTION
**Pull request by RohanDas28**

### CODE REVIEW

**Review by CodeRustyPro — CHANGES_REQUESTED** [review]
Just add a try except for edge cases error like no input etc ..

**Comment by RohanDas28** [comment]
Ya that would also work.. but for programs like these I guess break is the best option. So the code won't look complicated for beginners.

**Comment by CodeRustyPro** [comment]
> Ya that would also work.. but for programs like these I guess break is the best option. So the code won't look complicated for beginners.

By the way how do you know Harry bhai ?

**Comment by RohanDas28** [comment]
Yes I Do 😉

**Pull request closed without merging**
